#!/bin/bash

echo "Building external wireless modules (this will take some time)"
(
cd compat-drivers-3.8.3-2-snpu/ &&\
(
  KLIB_BUILD=`pwd`/.. ARCH=arm CROSS_COMPILE=`pwd`/../cross-toolchain/arm-fsl-linux-gnueabi/bin/arm-linux- make -j2 >/dev/null 2>&1
  if [ $? -ne "0" ] ; then
    echo "Failed to build external wireless modules"
    echo "Run the following command from compat-drivers-3.8.3-2-snpu/ to see full output"
    echo ""
    echo "KLIB_BUILD=\`pwd\`/.. ARCH=arm CROSS_COMPILE=\`pwd\`/../cross-toolchain/arm-fsl-linux-gnueabi/bin/arm-linux- make -j2"
    exit 1
  fi
  echo "External wireless modules successfully built"
  exit 0
)
)
